[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "build"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
